name: Publish AlmaLinux
description: A reusable action to publish the AlmaLinux image

inputs:
  tags:
    description: Docker tags
    required: true
  labels:
    description: Docker labels
    required: true

runs:
  using: "composite"
  steps:
    # needed to build multi-platform images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to CERN registry
      uses: docker/login-action@v2
      with:
        registry: registry.cern.ch
        username: ${{ secrets.CERN_REGISTRY_USERNAME }}
        password: ${{ secrets.CERN_REGISTRY_PASSWORD }}

    - run: echo "Publishing Docker images with tags '${{ inputs.tags }}' and labels '${{ inputs.labels }}'"

    - name: Publish AlmaLinux
      uses: docker/build-push-action@v3
      with:
        context: ./almalinux/
        file: ./almalinux/Dockerfile
        # support images for Intel and Apple Silicon processors
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
