
# SPDX-FileCopyrightText: 2025-2026 Northwestern University.
# SPDX-License-Identifier: MIT
#
# This is the Github action to build and publish the
# Github Container Resigstry (GHCR) hosted Invenio Debian base image.

# It is run on a schedule to keep the image fresh or manually to incorporate
# changes quicker (e.g. for improvements or security response). It is not run
# based on a tagged release model, bc this repository doesn't fit that model.
#
# Based on: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
#
# Naming schemes:
#   invenio:debian-python{python_version}
# where python_version is an anointed one
# because:
#  - Dockerfile not just for RDM
#  - short and parallels official Python image
#
#   invenio:{rdm_version}-debian
# where rdm_version is a currently supported one
# because:
#  - Python and other tools are indexed on RDM version
#  - doesn't mention RDM by name to
#      * not put off use by InvenioILS or Invenio framework
#      * not confuse and take up space of image that would install RDM in it
#  - short, with version first and os second to parallel choice process
#

on:
  schedule:
    - cron:  "0 3 * * 2"  # at 03:00 on Tuesday

  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-debian:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        # Under the hood, the images are aligned with RDM versions
        # because those guarantee a set of versioned languages/runtimes/tools
        # that work together. The image name keeps this implicit. It prevents
        # the image from squatting on a potential image that *would* include
        # the RDM application in it.
        rdm_version: ["13", "14"]
        # Define the specific variables for each version
        include:
          - rdm_version: "13"
            python_version: "3.11"  # just because known to work
            node_version: "22"  # just because known to work
            os_version: "trixie"  # just because known to work
          - rdm_version: "14"
            python_version: "3.14"
            node_version: "24"
            os_version: "trixie"

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v7

      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f  # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302  # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/invenio
          # always clobber previous tags
          tags: |
            type=raw,value=debian-python${{matrix.python_version}}
            type=raw,value=${{matrix.rdm_version}}-debian

      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  # v7.3.0
        with:
          context: ./debian/
          pull: true  # to pull fresh FROM image
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
            NODE_VERSION=${{ matrix.node_version }}
            OS_VERSION=${{ matrix.os_version }}
