# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2020 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
          include:
            - image-name: centos7:3.6
              python-version: 3.6
              cmd-args: -t inveniosoftware/centos7:3.6 ./centos7/python3.6/ --build-arg CENTOS_VERSION=7
              experimental: false

            - image-name: centos7:3.9
              python-version: 3.9
              cmd-args: -t inveniosoftware/centos7:3.9 ./centos7/python3.9/ --build-arg CENTOS_VERSION=7
              experimental: false

            - image-name: almalinux
              python-version: 3.9
              cmd-args: -t inveniosoftware/almalinux ./almalinux/ --build-arg LINUX_VERSION=9 --build-arg BUILDPLATFORM=linux/amd64
              experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build ${{ matrix.cmd-args }}

      - name: Run tests
        run: |
          docker run --name invenio-container -t -d inveniosoftware/${{ matrix.image-name }}
          docker cp ./tests/test_image_python.sh invenio-container:/home
          docker exec invenio-container chmod 777 /home/test_image_python.sh
          docker exec invenio-container /home/test_image_python.sh ${{ matrix.python-version }}
          docker cp invenio-container:/tmp/tests_output.txt .
          ./tests/assert_image_tests_passed.sh
