# SPDX-FileCopyrightText: 2020 CERN.
# SPDX-FileCopyrightText: 2026 Northwestern University.
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
          image-name: ["almalinux", "invenio-debian-rdm-v14"]
          include:
            - image-name: almalinux
              cmd-args: --tag inveniosoftware/almalinux ./almalinux/ --build-arg LINUX_VERSION=9 --build-arg BUILDPLATFORM=linux/amd64
              python-version: 3.9
              experimental: false
            # having to repeat the values in publish-debian-rdm is not ideal, but will do for now
            - image-name: invenio-debian-rdm-v14
              cmd-args: --tag inveniosoftware/invenio-debian-rdm-v14 ./debian/ --build-arg PYTHON_VERSION=3.14 --build-arg OS_VERSION=trixie --build-arg NODE_VERSION=24
              python-version: 3.14
              experimental: false

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Docker build
        run: docker build ${{ matrix.cmd-args }}

      - name: Run tests
        run: |
          docker run --name invenio-container --tty --detach inveniosoftware/${{ matrix.image-name }}
          docker cp ./tests/test_image_python.sh invenio-container:/home
          docker exec invenio-container chmod 777 /home/test_image_python.sh
          docker exec invenio-container /home/test_image_python.sh ${{ matrix.python-version }}
          docker cp invenio-container:/tmp/tests_output.txt .
          ./tests/assert_image_tests_passed.sh
